/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otel;

/**
 *
 * @author asus
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.lang.*;
import javax.swing.*;
import java.text.*;
import java.util.*;
import javax.swing.JButton;
public class odalar extends javax.swing.JFrame {

    /**
     * Creates new form odalar
     */
    giris g = new giris();
    public odalar() {
        initComponents();
        oda_id_getir(cb_oda_id);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tb_oda_durum = new javax.swing.JTextField();
        tb_oda_no = new javax.swing.JTextField();
        tb_oda_kisi = new javax.swing.JTextField();
        tb_oda_fiyat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cb_oda_id = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(250, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Oda Durum");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel2.setText("Odalar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel3.setText("Oda no");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel4.setText("Oda Fiyat");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel5.setText("Kişi Sayısı");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        getContentPane().add(tb_oda_durum, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 110, -1));
        getContentPane().add(tb_oda_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 110, -1));
        getContentPane().add(tb_oda_kisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 110, -1));
        getContentPane().add(tb_oda_fiyat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 110, -1));

        jButton1.setText("Çıkış");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        jButton2.setText("Kirala");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        cb_oda_id.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_oda_idİtemStateChanged(evt);
            }
        });
        getContentPane().add(cb_oda_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cb_oda_idİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_oda_idİtemStateChanged
        oda_getir(cb_oda_id);
    }//GEN-LAST:event_cb_oda_idİtemStateChanged

    /**
     * @param args the command line arguments
     */
    
    //Comboboxa oda idleri çekme
    public void oda_id_getir(JComboBox x)
    {
        x.removeAllItems();
        try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/otel?serverTimezone=UTC&useLegacyDatetimeCode=false","root","Umitcan123!");
            String sql ="Select oda_id from oda ";
            PreparedStatement pst=baglan.prepareStatement(sql);
            ResultSet rs =pst.executeQuery();
            
            while(rs.next())
            {
                String id = rs.getString("oda_id");
                x.addItem(id);
            }
            baglan.close();
        }
        catch (Exception e)
        {
            giris.messageBox(e.toString());
        }
        
    }
    public void oda_getir(JComboBox x)
    {
        String id= x.getSelectedItem().toString();
        try 
        {
         
            Class.forName("com.mysql.jdbc.Driver");
            Connection baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/otel?serverTimezone=UTC&useLegacyDatetimeCode=false","root","Umitcan123!");
            String sql ="Select * from oda where oda_id=?";
            PreparedStatement pst=baglan.prepareStatement(sql);
            pst.setString(1,id);
            ResultSet rs =pst.executeQuery();
            while(rs.next())
            {
                tb_oda_no.setText(rs.getString("oda_no"));
                tb_oda_kisi.setText(rs.getString("oda_kisi"));
                tb_oda_fiyat.setText(rs.getString("oda_fiyat")+ " TL");
                String a=rs.getString("durum");
                if (a.equals("0")) 
                {
                    tb_oda_durum.setText("Boş");
                }
                else
                {
                    tb_oda_durum.setText("Dolu");
                }
                
            }
        } 
        catch (Exception e) 
        {
            giris.messageBox(e.toString());
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(odalar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(odalar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(odalar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(odalar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new odalar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_oda_id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tb_oda_durum;
    private javax.swing.JTextField tb_oda_fiyat;
    private javax.swing.JTextField tb_oda_kisi;
    private javax.swing.JTextField tb_oda_no;
    // End of variables declaration//GEN-END:variables
}
